id: File GTI assessment - GoogleThreatIntelligence
version: -1
contentitemexportablefields:
  contentitemfields: {}
name: File GTI assessment - GoogleThreatIntelligence
description: Get file GTI assessment using the GoogleThreatIntelligence integration.
starttaskid: "0"
tasks:
  "0":
    id: "0"
    taskid: cdcd5ce3-8d4a-4981-89ff-e94904ef9de0
    type: start
    task:
      id: cdcd5ce3-8d4a-4981-89ff-e94904ef9de0
      version: -1
      name: ""
      iscommand: false
      brand: ""
      description: ''
    nexttasks:
      '#none#':
      - "19"
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 1155,
          "y": -23
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "1":
    id: "1"
    taskid: e5be9a7a-708a-4976-84de-f60213e157f0
    type: title
    task:
      id: e5be9a7a-708a-4976-84de-f60213e157f0
      version: -1
      name: Enrich using GoogleThreatIntelligence
      type: title
      iscommand: false
      brand: ""
      description: ''
    nexttasks:
      '#none#':
      - "26"
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 1585,
          "y": 370
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "7":
    id: "7"
    taskid: 10dbc242-e1c6-4746-852e-3777185de510
    type: title
    task:
      id: 10dbc242-e1c6-4746-852e-3777185de510
      version: -1
      name: Done
      type: title
      iscommand: false
      brand: ""
      description: ''
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 1155,
          "y": 680
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "19":
    id: "19"
    taskid: 3d9a4d8a-9a38-45a5-86d0-d9707b8f9bf1
    type: condition
    task:
      id: 3d9a4d8a-9a38-45a5-86d0-d9707b8f9bf1
      version: -1
      name: Is GoogleThreatIntelligence enabled?
      description: Checks if there is an active instance of the Virus Total Private API enabled.
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      '#default#':
      - "7"
      "yes":
      - "1"
    separatecontext: false
    conditions:
    - label: "yes"
      condition:
      - - operator: isExists
          left:
            value:
              complex:
                root: modules
                filters:
                - - operator: isEqualString
                    left:
                      value:
                        simple: modules.brand
                      iscontext: true
                    right:
                      value:
                        simple: GoogleThreatIntelligence
                    ignorecase: true
                - - operator: isEqualString
                    left:
                      value:
                        simple: modules.state
                      iscontext: true
                    right:
                      value:
                        simple: active
                    ignorecase: true
                accessor: brand
            iscontext: true
          right:
            value: {}
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 1155,
          "y": 151
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "26":
    id: "26"
    taskid: 333b460a-414c-4ccd-834c-4aa3c3bedb99
    type: regular
    task:
      id: 333b460a-414c-4ccd-834c-4aa3c3bedb99
      version: -1
      name: 'Getting file GTI assessment '
      description: Checks the file reputation of the specified hash.
      script: GoogleThreatIntelligence|||file
      type: regular
      iscommand: true
      brand: GoogleThreatIntelligence
    nexttasks:
      '#none#':
      - "7"
    scriptarguments:
      file:
        simple: ${inputs.FileHash}
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 1585,
          "y": 510
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 768,
        "width": 810,
        "x": 1155,
        "y": -23
      }
    }
  }
inputs:
- key: FileHash
  value:
    complex:
      root: File
      accessor: SHA256
      transformers:
      - operator: append
        args:
          item:
            value:
              simple: File.SHA1
            iscontext: true
      - operator: append
        args:
          item:
            value:
              simple: File.MD5
            iscontext: true
  required: false
  description: File Hash from which to get GTI assessment
  playbookInputQuery:
outputs:
- contextPath: File.MD5
  description: Bad MD5 hash.
  type: Unknown
- contextPath: File.SHA1
  description: Bad SHA1 hash.
  type: Unknown
- contextPath: File.SHA256
  description: Bad SHA256 hash.
  type: Unknown
- contextPath: File.Relationships.EntityA
  description: The source of the relationship.
  type: String
- contextPath: File.Relationships.EntityB
  description: The destination of the relationship.
  type: String
- contextPath: File.Relationships.Relationship
  description: The name of the relationship.
  type: String
- contextPath: File.Relationships.EntityAtype
  description: The type of the source of the relationship.
  type: String
- contextPath: File.Relationships.EntityBtype
  description: The type of the destination of the relationship.
  type: String
- contextPath: File.Malicious.Vendor
  description: For malicious files, the vendor that made the decision.
  type: Unknown
- contextPath: File.Malicious.Detections
  description: For malicious files, the total number of detections.
  type: Unknown
- contextPath: File.Malicious.TotalEngines
  description: For malicious files, the total number of engines that checked the file hash.
  type: Unknown
- contextPath: DBotScore.Indicator
  description: The indicator that was tested.
  type: Unknown
- contextPath: DBotScore.type
  description: The indicator type.
  type: Unknown
- contextPath: DBotScore.Vendor
  description: The vendor used to calculate the DBot score.
  type: Unknown
- contextPath: DBotScore.Score
  description: The actual score.
  type: Number
- contextPath: DBotScore.Reliability
  description: Reliability of the source providing the intelligence data.
  type: String
- contextPath: GoogleThreatIntelligence.Assessment.attributes.gti_assessment.threat_score.value
  description: The threat score of the assessment.
  type: Number
- contextPath: GoogleThreatIntelligence.Assessment.attributes.gti_assessment.severity.value
  description: The severity of the assessment.
  type: string
- contextPath: GoogleThreatIntelligence.Assessment.attributes.gti_assessment.verdict.value
  description: The verdict of the assessment.
  type: String
- contextPath: GoogleThreatIntelligence.Assessment.type
  description: type of the indicator (file).
  type: String
- contextPath: GoogleThreatIntelligence.Assessment.id
  description: type ID of the indicator.
  type: String
- contextPath: GoogleThreatIntelligence.Assessment.links.self
  description: Link to the response.
  type: Unknown
tests:
- No tests (auto formatted)
fromversion: 6.10.0
