exclude: .devcontainer/|.vscode|Pipfile.lock|.gitlab/ci/|docs
files: ''
repos:
- repo: https://github.com/sourcery-ai/sourcery
  rev: v1.6.0
  hooks:
  - id: sourcery
    config_file: .sourcery.yaml
    args:
    - --no-summary
    - --diff
    - git diff HEAD
    - --fix
    args:nightly:
    - --no-summary
    - --diff
    - git diff HEAD
    args:ci:
    - --no-summary
    - --diff
    - git diff HEAD
    skip: true
